Add Image Component
DTS-STN/DECD-Design-System pull request #74
Opened 2021-12-10 17:50 UTC by jvaddinen

2021-12-16 14:45 UTC, AnthonyA44 commented on src/components/Image/Image.js
> +  id: PropTypes.string,
Minor updates needed to the explanation text for each parameter, to explain the individual parameters usage :)

2021-12-16 14:46 UTC, AnthonyA44 approved these changes

2021-12-16 14:48 UTC, AnthonyA44 commented on src/components/Image/Image.js
> +  id: PropTypes.string.isRequired,
duplicate id props

2021-12-16 14:48 UTC, AnthonyA44 requested changes
some minor comment changes and duplicate parameters

2021-12-16 21:34 UTC, jvaddinen commented on src/components/Image/Image.js
> +  id: PropTypes.string.isRequired,
Removed

2021-12-17 15:58 UTC, AnthonyA44 approved these changes
Everything looks good. Component works as intended on external repo :)

2021-12-17 16:27 UTC, merged